repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    - id: check-yaml
      files: \.yml$
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: detect-private-key
    - id: mixed-line-ending
    - id: check-toml
    - id: requirements-txt-fixer
    - id: no-commit-to-branch
      args: [--branch, main]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: 'v9.16.0'
    hooks:
    - id: commitlint
      stages: [commit-msg]

  # black - formatting
  - repo: https://github.com/psf/black
    rev: '24.8.0'
    hooks:
    - id: black

  # flake8 - liniting
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.0'
    hooks:
    - id: flake8
      exclude: tests/
