version: 2.1
orbs:
  python: .circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    executor:  python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: pytest -v
# Orchestrate jobs using workflows
workflows:
  sample:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
