version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    executor:  python/default
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            pip install --no-cache-dir --upgrade pip \
            && pip install --no-cache-dir -r requirements/dev.txt
            python -m pip install .
      - run:
          name: Run Tests
          command: pytest -v
# Orchestrate jobs using workflows
workflows:
  taskbuddy:
    jobs:
      - build-and-test
