version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12
    executor:  python/default
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run:
          name: Set PYTHONPATH
          command: echo "export PYTHONPATH=./taskbuddy" >> $BASH_ENV
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest -v
# Orchestrate jobs using workflows
workflows:
  sample:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
